CREATE TABLE VULN.product (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    description VARCHAR(255)
); 

ALTER TABLE VULN.product ADD UNIQUE(name);


ALTER TABLE VULN.product MODIFY name NVARCHAR(255)

SELECT *  FROM VULN.product


--documentmasster table 


CREATE TABLE VULN.DOCUMENTMASTER(
	DocumentNumber NVARCHAR(255),
    DocumentName NVARCHAR(255),
    DocumentProduct NVARCHAR(255),
    DocumentAuthor NVARCHAR(255),
    CreatedDate NVARCHAR(255),
    ReferenceID  INT NOT NULL AUTO_INCREMENT PRIMARY KEY
) AUTO_INCREMENT =100


CREATE TABLE VULN.DOCUMENT(
	Doc_NUMBER NVARCHAR(255),
    Doc_Name NVARCHAR(255),
	Revision NVARCHAR(255),
    Description NVARCHAR(255),
	DocumentAuthor NVARCHAR(255),
	LocalFilePath	NVARCHAR(255),
    CreatedDate NVARCHAR(255),
    ModifiedDate NVARCHAR(255),
    Product_name NVARCHAR(255),
    ReferenceID  INT NOT NULL AUTO_INCREMENT PRIMARY KEY
) AUTO_INCREMENT =800


SELECT * FROM VULN.DOCUMENT


SELECT * FROM VULN.DOCUMENT where Product_name='product1'

CREATE TABLE VULN.USERS(
	Username NVARCHAR(255),
	password NVARCHAR(255),
    role NVARCHAR(255), 
	
    REFERENCE_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
)AUTO_INCREMENT = 300

insert into VULN.USERS(Username,password,role,product_access)values('admin','admin','admin','all')

TRUNCATE TABLE VULN.USERS

ALTER TABLE VULN.USERS ADD PRODUCT_ACCESS NVARCHAR(255)  


SELECT * FROM VULN.USERS

delete from VULN.USERS WHERE username is null or username ='null'

ALTER TABLE VULN.products MODIFY ID INT UNSIGNED;

ALTER TABLE VULN.USERS DROP FOREIGN KEY PA_FRNK;

CREATE TABLE VULN.DOCUMENT_ACL(
	DocumentID BIGINT ,
    ProductID BIGINT,
    USER_ID BIGINT,
    CREAT BOOLEAN,
    EDIT BOOLEAN,
    DELET BOOLEAN,
    VIE BOOLEAN,
    REFERENCE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	FOREIGN KEY (DocumentID) REFERENCES DOCUMENTMASTER(ReferenceID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(REFERENCE_ID)
)AUTO_INCREMENT = 500


SHOW TABLES FROM VULN;

DROP TABLE VULN.document
DROP TABLE VULN.document_acl
DROP TABLE VULN.documentmaster
DROP TABLE VULN.product
DROP TABLE VULN.product_acl
DROP TABLE VULN.products
DROP TABLE VULN.users




